<div class="actions">
    <?php $_order= $block->getOrder(); ?>
    <?php if($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
    <a href="#" data-post="<?php echo $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)->getPostData($block->getReorderUrl($_order))?>"
       class="action order">
        <span> Reorder </span>
    </a>
    <?php endif; ?>

    <?php if($_order->canCancel()) : ?>
    <a href="<?= $this->getUrl('helloworld/quote/cancel').'order_id/'.$_order->getEntityId(); ?>"
       class="action cancel order">
        <span> Cancel Order </span>
    </a>
    <?php endif; ?>
    <a class="action print" href="<?= $block->getPrintUrl($_order)?>" onclick="this.target='_blank';">
        <span>Print Order</span>
    </a>
    <?= $block->getChildHtml()?>
</div>